### ISSUE TITLE
Deployment on Heroku

### ISSUE THREAD

**Issue by PaulCailly** [tsmean/tsmean#2]
Hi,

I'm trying to deploy my project on Heroku but I have lot of errors..

` > uws@0.14.5 install /tmp/build/node_modules/uws
       > node-gyp rebuild > build_log.txt 2>&1 || exit 0

       > ts-mean@4.0.1 postinstall /tmp/build
       > npm run gitinit && ts-node install.ts

       > ts-mean@4.0.1 gitinit /tmp/build
       > git submodule init && git submodule update

       fatal: Not a git repository (or any of the parent directories): .git

       npm ERR! Linux 4.4.0-97-generic
       npm ERR! argv "/tmp/build/.heroku/node/bin/node" "/tmp/build/.heroku/node/bin/npm" "run" "gitinit"
       npm ERR! node v6.11.5
       npm ERR! npm  v3.10.10
       npm ERR! code ELIFECYCLE
       npm ERR! ts-mean@4.0.1 gitinit: `git submodule init && git submodule update`
       npm ERR! Exit status 128
       npm ERR!
       npm ERR! Failed at the ts-mean@4.0.1 gitinit script 'git submodule init && git submodule update'.
       npm ERR! Make sure you have the latest version of node.js and npm installed.
       npm ERR! If you do, this is most likely a problem with the ts-mean package,
       npm ERR! not with npm itself.
       npm ERR! Tell the author that this fails on your system:
       npm ERR!     git submodule init && git submodule update
       npm ERR! You can get information on how to open an issue for this project with:
       npm ERR!     npm bugs ts-mean
       npm ERR! Or if that isn't available, you can get their info via:
       npm ERR!     npm owner ls ts-mean
       npm ERR! There is likely additional logging output above.

       npm ERR! Please include the following file with any support request:
       npm ERR!     /tmp/build/npm-debug.log

       npm ERR! Linux 4.4.0-97-generic
       npm ERR! argv "/tmp/build/.heroku/node/bin/node" "/tmp/build/.heroku/node/bin/npm" "install" "--unsafe-perm" "--userconfig" "/tmp/build/.npmrc"
       npm ERR! node v6.11.5
       npm ERR! npm  v3.10.10
       npm ERR! code ELIFECYCLE
       npm ERR! ts-mean@4.0.1 postinstall: `npm run gitinit && ts-node install.ts`
       npm ERR! Exit status 1
       npm ERR!
       npm ERR! Failed at the ts-mean@4.0.1 postinstall script 'npm run gitinit && ts-node install.ts'.
       npm ERR! Make sure you have the latest version of node.js and npm installed.
       npm ERR! If you do, this is most likely a problem with the ts-mean package,
       npm ERR! not with npm itself.
       npm ERR! Tell the author that this fails on your system:
       npm ERR!     npm run gitinit && ts-node install.ts
       npm ERR! You can get information on how to open an issue for this project with:
       npm ERR!     npm bugs ts-mean
       npm ERR! Or if that isn't available, you can get their info via:
       npm ERR!     npm owner ls ts-mean
       npm ERR! There is likely additional logging output above.

       npm ERR! Please include the following file with any support request:
       npm ERR!     /tmp/build/npm-debug.log

-----> Build failed

       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys `

Maybe you have an idea ?

**Comment by bersling** [comment]
looks like you're missing a dependency?
