### ISSUE TITLE
Chose which tables are created on  app init

### ISSUE THREAD

**Issue by caohothang** [tsmean/tsmean#33]
how i can turn off auto create table user + animal models

**edit**: Please add the description of your issue on the description, not in the title

**Comment by AngelMunoz** [comment]
Hello @caohothang 
you can either manually list each entity you want to register on your database here
https://github.com/tsmean/tsmean/blob/master/backend/src/database/database.providers.ts#L23
or remove **[name].entity.ts** files and [tyeorm](https://typeorm.io) will not recognize them.
<br>
for more information about entities and typeorm related configuration on the connection you can check this link http://typeorm.io/#/connection

**Comment by caohothang** [comment]
@AngelMunoz  thanks for your support i will try it.
