### ISSUE TITLE
Path incorrect when i use npm start

### ISSUE THREAD

**Issue by siliconprime-thangcao** [tsmean/tsmean#37]
ERROR in node_modules/@tsmean/shared/src/models/user.model.ts(1,24): error TS2307: Cannot find module '../../../frontend/resource/src/app/resource/resource'.

i think it should "./resource.model" but not sure why it build to '../../../frontend/resource/src/app/resource/resource'.

**Comment by AngelMunoz** [comment]
does this happen on a deployment build? or when you run the development setup?

**Comment by ghost** [comment]
I am getting this issue at the basic debug build as well.

**Comment by jokke009** [comment]
I also ran into this issue a few times when deploying.
The mistake was that I accidently performed an npm install in the frontend sub dir before running it. I only needed to do the npm install --unsafe-perm in the root directory (triggering the lerna to do the rest so to say..). So in fact there's nothing wrong. rtfm.  

Hope it helps. 
Cheers,

**Comment by AngelMunoz** [comment]
Sorry for the late response, but I can see @jokke009 's coment as a valid one since after installing, lerna handles the monorepo's structure

you can omit the `npm install` by just running `lerna bootstrap` but, `npm install` will also run `lerna bootstrap` at the end of the installation process
